{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "789bf5d8_6334a8e1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 7
      },
      "lineNbr": 0,
      "author": {
        "id": 166
      },
      "writtenOn": "2024-04-04T12:24:06Z",
      "side": 1,
      "message": "Yeah, it should 401, but server is returning, hence the message check, but it\u0027s likely a bug in the control server.\nOne lead I\u0027m investigating is that we catch the exception somewhere, and instead of re-raising it, we copy the message in a new exception (so it gets default status_code 400)",
      "revId": "14725f0d80f223277f2f6b43c735aee0a82508e6",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4a097338_81ea2b04",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 7
      },
      "lineNbr": 0,
      "author": {
        "id": 1440
      },
      "writtenOn": "2024-04-09T08:27:04Z",
      "side": 1,
      "message": "In my opinion the client should display the content of the error message returned by the API. It should not interpret it, just basic stderr.\n\nChecking the value of the error message is not good, because this check will fail as soon as we change the error message.\n\nSo if the problem is the error message not displayed, then this patch should display the content of the error message.\n\nIf the client is displaying the error message, but the error message is not explicit/good enough, then we should update the error message on the server, not the client.\n\nAnother solution is to send the error codes in the API. But this solution will require some changes in the server first, and I don\u0027t know if this is what we want.",
      "revId": "14725f0d80f223277f2f6b43c735aee0a82508e6",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "dcf79f1c_d8f20959",
        "filename": "dciclient/printer.py",
        "patchSetId": 7
      },
      "lineNbr": 124,
      "author": {
        "id": 648
      },
      "writtenOn": "2024-04-03T23:12:59Z",
      "side": 1,
      "message": "I don\u0027t think you need to parse the message, just checking the return code and re-raising an exception should work: it goes to the catch-all except below and print the message returned from DCC.\nAs a side note: I think https://github.com/redhat-cip/dci-control-server/blob/master/dci/auth_mechanism.py#L206 should return with status_code\u003d401 @gvincent",
      "revId": "14725f0d80f223277f2f6b43c735aee0a82508e6",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0"
    }
  ]
}