{
  "comments": [
    {
      "key": {
        "uuid": "5a682502_58d6c1c6",
        "filename": "dciclient/v1/shell_commands/__init__.py",
        "patchSetId": 4
      },
      "lineNbr": 50,
      "author": {
        "id": 30
      },
      "writtenOn": "2016-03-01T21:12:39Z",
      "side": 1,
      "message": "The order is wrong",
      "revId": "36d3ebc21dcddd058b97c5c82ac6af892e4867a7",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}